apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyyhd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyyhd
  template:
    metadata:
      labels:
        app: tyyhd
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: tyyhd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0a78deb4-72dc-4867-81ae-2e8bde694297"
        - name: Vless_Path
          value: "/vl54t5gf"
        - name: Vmess_UUID
          value: "0a78deb4-72dc-4867-81ae-2e8bde694297"
        - name: Vmess_Path
          value: "/vmug8hf"
        - name: Share_Path
          value: "/v2link"
